# -*- coding: utf-8 -*-
"""Notebook_2 Embeddings and Faiss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBCZ336DbVui4T7hlrx8M4c0d_a98un3
"""

# Install dependencies
!pip install -q sentence-transformers faiss-cpu langchain-huggingface

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from langchain_huggingface import HuggingFaceEmbeddings
import faiss
from tqdm.auto import tqdm

# Upload Preprocessed Dataset
from google.colab import files
uploaded = files.upload()

# Loading the preprocessed dataset
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print(f"Loaded dataset with shape: {df.shape}")
display(df.sample(3))

# Preparing Text for Embedding

# Ensuring all text inputs are strings and replacing NaNs
QnA = [(str(q) if pd.notna(q) else "") for q in (df['Question'] + " " + df['Response'])]

print("Text prepared for embedding.")

# Loading Embedding Models

# MiniLM model for general-purpose semantic embeddings
model_general_name = "sentence-transformers/all-MiniLM-L6-v2"
model_general = HuggingFaceEmbeddings(
    model_name=model_general_name,
    model_kwargs={'device': 'cpu'},
    encode_kwargs={'normalize_embeddings': True}
)

# PubMedBERT model for clinical domain-specific embeddings
model_medical_name = "neuml/pubmedbert-base-embeddings"
model_medical = HuggingFaceEmbeddings(
    model_name=model_medical_name,
    model_kwargs={'device': 'cpu'},
    encode_kwargs={'normalize_embeddings': True}
)

print("Embedding models loaded successfully.")

# Generating and Storing Dual Embeddings

# Generating general-purpose embeddings
print("Generating general-purpose MiniLM embeddings...")
df['embedding_minilm'] = model_general.embed_documents(QnA)

# Generating domain-specific PubMedBERT embeddings
print("Generating medical-domain PubMedBERT embeddings...")
df['embedding_pubmed'] = model_medical.embed_documents(QnA)

print("Dual embeddings generated successfully.")

# Building and Saving FAISS Index for MiniLM (Cosine Similarity)

# Converting MiniLM embeddings into a NumPy array
embedding_matrix_minilm = np.array(df['embedding_minilm'].tolist()).astype('float32')

# Normalizing embeddings to unit length
faiss.normalize_L2(embedding_matrix_minilm)

# Creating FAISS index for cosine similarity
index_minilm = faiss.IndexFlatIP(embedding_matrix_minilm.shape[1])
index_minilm.add(embedding_matrix_minilm)

# Saving FAISS index
faiss.write_index(index_minilm, "faiss_minilm_cosine.index")

print("MiniLM FAISS index (cosine similarity) built and saved.")

# Building and Saving FAISS Index for PubMedBERT (Cosine Similarity)

# Converting PubMedBERT embeddings into a NumPy array
embedding_matrix_pubmed = np.array(df['embedding_pubmed'].tolist()).astype('float32')

# Normalizing embeddings to unit length
faiss.normalize_L2(embedding_matrix_pubmed)

# Creating FAISS index for cosine similarity
index_pubmed = faiss.IndexFlatIP(embedding_matrix_pubmed.shape[1])
index_pubmed.add(embedding_matrix_pubmed)

# Saving FAISS index
faiss.write_index(index_pubmed, "faiss_pubmed_cosine.index")

print("PubMedBERT FAISS index (cosine similarity) built and saved.")

# Saving the DataFrame

# Saving full DataFrame including both embeddings to a .pkl file
output_path = "dual_embeddings.pkl"
df.to_pickle(output_path)

print(f"Enriched dataset saved as {output_path}.")