# -*- coding: utf-8 -*-
"""Notebook_1 Data Preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfRV2q60KUUJv3Tk-_778vnuTo1Dj6M_

# MOMCare: Data Preprocessing and Metadata Addition (Zarak)
"""

# Install dependencies
!pip install -q beautifulsoup4

!pip install -q sentence-transformers

# Imports
import pandas as pd
import re
from bs4 import BeautifulSoup
from google.colab import files
import io
import nltk
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Extended stopwords for clinical context
clinical_stopwords = set([
    "patient", "doctor", "nurse", "hospital", "clinic", "healthcare",
    "symptom", "treatment", "medical", "diagnosis", "disease", "illness"
])
stop_words.update(clinical_stopwords)

# Upload files
uploaded = files.upload()

print(uploaded.keys()) # check directory for uploaded files

print(uploaded.keys())

# Load datasets
ppd_df = pd.read_excel(io.BytesIO(uploaded['1_PPD_Dataset.xlsx']))
edge_df = pd.read_csv(io.BytesIO(uploaded['2_Edge_Cases Dataset.csv']))
counsel_df = pd.read_csv(io.BytesIO(uploaded['3_Counsel_Chat_Dataset.csv']))
motiv_df = pd.read_csv(io.BytesIO(uploaded['4_Motivational_Dataset.csv']), encoding='latin1')


#  Add Domain Labels
ppd_df["Domain"] = "PPD"
edge_df["Domain"] = "Edge_Cases"
counsel_df["Domain"] = "Counsel_Chat"
motiv_df["Domain"] = "Motivational"

# Show 5 random rows from each dataset
print("PPD Dataset Sample:")
display(ppd_df.sample(5))

print("Edge Cases Dataset Sample:")
display(edge_df.sample(5))

print("Counsel Chat Dataset Sample:")
display(counsel_df.sample(5))

print("Motivational Dataset Sample:")
display(motiv_df.sample(5))

print(ppd_df.columns.tolist())
print(edge_df.columns.tolist())
print(counsel_df.columns.tolist())
print(motiv_df.columns.tolist())

'''# Strip HTML from Response in counsel_df
def strip_html(text):
    if pd.isna(text): #(I added this but this didnt work)
        return text  # leave NaN as is (NEW ADD)
    return BeautifulSoup(text, "html.parser").get_text()


counsel_df["Response"] = counsel_df["Response"].apply(strip_html)

print("Counsel Chat Dataset (Cleaned):")
display(counsel_df.sample(5))'''

import unicodedata

def clean_text(text):
    text = unicodedata.normalize("NFKD", str(text))
    text = text.encode("ascii", "ignore").decode("ascii")
    return text.strip()

# Applying cleaning to each dataset
for df_clean in [ppd_df, edge_df, counsel_df, motiv_df]:
    df_clean["Question"] = df_clean["Question"].apply(clean_text)
    df_clean["Response"] = df_clean["Response"].apply(clean_text)

# Remove rows with missing values
for df in [ppd_df, edge_df, counsel_df, motiv_df]:
    df.dropna(subset=["Question", "Response"], inplace=True)

# Remove duplicates
for df in [ppd_df, edge_df, counsel_df, motiv_df]:
    df.drop_duplicates(subset=["Question", "Response"], inplace=True)

# Strip HTML from Response in counsel_df
def strip_html(text):
    return BeautifulSoup(text, "html.parser").get_text()

counsel_df["Response"] = counsel_df["Response"].apply(strip_html)

print("Counsel Chat Dataset (Cleaned):")
display(counsel_df.sample(5))

# Drop unwanted columns
for df in [ppd_df, edge_df, counsel_df, motiv_df]:
    for col in ["norm_q", "norm_a"]:  # Iterate through columns to drop
        if col in df.columns:  # Check if column exists in DataFrame
            df.drop(columns=[col], inplace=True)  # Drop column if present

# Strip leading/trailing whitespace
for df in [ppd_df, edge_df, counsel_df, motiv_df]:
    df["Question"] = df["Question"].str.strip()
    df["Response"] = df["Response"].str.strip()

# Merge all 4 cleaned datasets
df = pd.concat([ppd_df, edge_df, counsel_df, motiv_df], ignore_index=True)

'''category_keywords = {
    "Mental & Physical Health Support": ["depression", "anxiety", "fatigue", "insomnia", "headache"],
    "Relationship & Social Support": ["husband", "partner", "family", "friend", "in-laws", "mother"],
    "Parenting & Baby Care Stress": ["baby", "breastfeeding", "crying", "sleep", "child", "feeding"],
    "Self-care & Coping Strategies": ["exercise", "therapy", "self-care", "routine", "relax", "cope"],
    "Crisis & Emergency Support": ["suicide", "kill", "die", "self-harm", "cutting", "jump", "emergency"],
    "Follow-up & Continuous Support": ["still feel", "again", "keep happening", "not improving"]
}'''

'''# Category Assignment Function (regex based)
def assign_category(question):
    question_lower = question.lower()
    for category, keywords in category_keywords.items():
        for kw in keywords:
            if re.search(r'\b' + re.escape(kw) + r's?\b', question_lower):
                return category
    return "Uncategorized"'''

!pip install --upgrade transformers --upgrade-strategy eager
!pip install --upgrade accelerate

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

#Importing Embedding Model
# Expanded Category Keywords
category_keywords = {
    "Mental & Physical Health Support": [
        "depression", "anxiety", "fatigue", "insomnia", "headache", "panic", "overwhelmed", "mental health", "sadness", "emotions"
    ],
    "Relationship & Social Support": [
        "husband", "partner", "family", "friend", "fight", "mother", "father", "support", "communication", "lonely"
    ],
    "Parenting & Baby Care Stress": [
        "baby", "breastfeeding", "crying", "sleep", "child", "feeding", "newborn", "infant", "childbirth", "motherhood"
    ],
    "Self-care & Coping Strategies": [
        "exercise", "therapy", "self-care", "routine", "relax", "cope", "mindfulness", "journaling", "walk", "breathing"
    ],
    "Crisis & Emergency Support": [
        "suicide", "kill", "die", "self-harm", "cutting", "jump", "emergency", "harm myself", "life danger", "hopeless"
    ],
    "Follow-up & Continuous Support": [
        "still feel", "again", "keep happening", "not improving", "relapse", "feeling worse", "therapy again", "backslide", "return", "continue"
    ],
    "General Mental Health Support": [
        "anxiety", "trauma", "therapy", "counseling", "mental", "depressed", "self-esteem", "trust", "emotion"
    ],
    "Motivational/Resilience Support": [
        "affirmation", "resilience", "self-esteem", "healing", "positivity", "overcoming", "strength", "hope", "empowerment"
    ]

}

# Synthetic labeled examples
synthetic_examples = {
    "Mental & Physical Health Support": [
        "Why do I feel so empty even after giving birth?",
        "I'm anxious all the time about everything.",
        "Sleep feels impossible lately, what can I do?",
        "I constantly feel tired, even with rest.",
        "Sometimes I get headaches after feeding my baby.",
        "Is it normal to feel emotionally numb postpartum?",
        "I'm feeling very panicked these days.",
        "My emotions are all over the place.",
        "I feel a deep sadness that won't go away.",
        "I have trouble managing my stress after delivery."
    ],
    "Relationship & Social Support": [
        "My husband doesn’t understand my feelings after birth.",
        "I feel distant from my family since I became a mother.",
        "My friends have disappeared since I had the baby.",
        "I feel lonely even when people are around me.",
        "My partner and I argue all the time now.",
        "How do I talk to my mother-in-law about my needs?",
        "I feel unsupported by my loved ones.",
        "Why do I feel isolated from my friends after delivery?",
        "I need better communication with my spouse.",
        "How can I rebuild my support system?"
    ],
    "Parenting & Baby Care Stress": [
        "Why won't my baby stop crying?",
        "I'm so tired of changing diapers all day.",
        "Breastfeeding is so painful for me.",
        "My baby never sleeps through the night.",
        "I can't soothe my infant when she's fussy.",
        "Feeding the baby feels like a huge stressor.",
        "How do I deal with newborn sleep issues?",
        "My child refuses to eat, and I'm worried.",
        "Being a mother is harder than I thought.",
        "Colic is driving me crazy, help!"
    ],
    "Self-care & Coping Strategies": [
        "How can I find time for myself with a newborn?",
        "Are there exercises safe for postpartum moms?",
        "Would journaling help my stress?",
        "What are some quick mindfulness exercises?",
        "Is therapy recommended for new moms?",
        "I need a daily routine to feel stable.",
        "Breathing exercises for calming down?",
        "What small self-care routines can I do?",
        "How can I relax when I feel so busy?",
        "Tips to cope with feeling overwhelmed?"
    ],
    "Crisis & Emergency Support": [
        "Sometimes I think about ending it all.",
        "I feel like hurting myself, what should I do?",
        "Is there a crisis hotline I can call?",
        "I’m scared I might harm myself.",
        "Emergency help for postpartum depression?",
        "I feel unsafe being alone right now.",
        "What to do if I feel like jumping off?",
        "I'm scared I might hurt the baby or myself.",
        "How do I get immediate mental health support?",
        "I feel completely hopeless."
    ],
    "Follow-up & Continuous Support": [
        "My depression is returning after feeling better.",
        "What if therapy doesn't help anymore?",
        "Why am I feeling bad again after recovery?",
        "I keep sliding back into sadness.",
        "Is it normal to need ongoing therapy?",
        "How to handle relapse after postpartum depression?",
        "My emotions are worsening again, help.",
        "Continuous support for long-term postpartum care?",
        "I feel like I'm back to square one.",
        "Is it bad if postpartum depression symptoms return?"
    ],
    "General Mental Health Support": [
        "I have trouble trusting people after trauma.",
        "Why do I feel depressed even when things seem fine?",
        "Therapy seems scary, how do I start?",
        "I feel stuck emotionally, what can I do?",
        "How to rebuild self-esteem after a breakup?",
        "Why do I push people away emotionally?",
        "How can therapy help with emotional issues?",
        "I want to find emotional balance again.",
        "Anxiety makes daily tasks impossible for me.",
        "I feel misunderstood by everyone."
    ],
    "Motivational/Resilience Support": [
        "How can I stay positive during hard times?",
        "What affirmations help boost self-confidence?",
        "Stories of people overcoming depression?",
        "Ways to build resilience after trauma?",
        "I want to feel strong again.",
        "How can I cultivate hope daily?",
        "Motivational quotes for healing?",
        "Activities that build emotional strength?",
        "Tips for bouncing back from failure?",
        "I want to feel empowered again."
    ]
}

# Embedding Model (clinical fine-tuned not mini lm)

embed_model = SentenceTransformer('neuml/pubmedbert-base-embeddings')

#embed_model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
#embed_model = SentenceTransformer('pritamdeka/BioBERT-mnli-snli-scinli-scitail-mednli-stsb')

# Preparing synthetic embeddings
synthetic_questions = []
synthetic_labels = []
for label, examples in synthetic_examples.items():
    synthetic_questions.extend(examples)
    synthetic_labels.extend([label] * len(examples))

synthetic_embeddings = embed_model.encode(synthetic_questions)

# Embedding-Based Assignment
def assign_by_embedding(question):
    question_embed = embed_model.encode([question])[0]
    sims = cosine_similarity([question_embed], synthetic_embeddings)[0]
    best_idx = np.argmax(sims)
    best_score = sims[best_idx]
    best_label = synthetic_labels[best_idx]

    if best_score > 0.65:  # Threshold setting to 0.65 simil
        return best_label
    else:
        return "Uncategorized"

# Final Hybrid Category Assignment
def assign_category_hybrid(question):
    # Trying keyword match first
    cat = None
    question_lower = question.lower()
    for category, keywords in category_keywords.items():
        for kw in keywords:
            if re.search(r'\b' + re.escape(kw) + r's?\b', question_lower):
                cat = category
                break
        if cat:
            break

    if cat:
        return cat
    else:
        return assign_by_embedding(question)

# Urgency Flag Function
def check_urgency(text):
    crisis_words = ["suicide", "kill myself", "self-harm", "die", "jump", "cutting"]
    return any(word in text.lower() for word in crisis_words)

# Keyword Tag Extractor (nltk based)
def extract_keywords(text):
    words = re.findall(r'\b\w+\b', str(text).lower())
    keywords = [word for word in words if word not in stop_words and len(word) > 3]
    return ", ".join(keywords[:5])

# Adding Metadata Columns
df['question_length'] = df['Question'].str.split().apply(len)
df['answer_length'] = df['Response'].astype(str).str.split().apply(len)
df['Category'] = df['Question'].apply(assign_category_hybrid)
df['is_urgent'] = df['Question'].apply(check_urgency)
df['keyword_tags'] = df['Question'].apply(extract_keywords)

print(df.shape)
display(df.sample(5))

'''# Split dataset into training (80%) and testing (20%)
train_df, test_df = train_test_split(df, test_size=0.1, random_state=42)

print("Training Data Size:", train_df.shape)
print("Testing Data Size:", test_df.shape)'''

# Save final enriched dataset
df.to_csv("embedded_dataset.csv", index=False)
print("Metadata added successfully! The dataset is saved as 'embedded_dataset.csv'")

# Download the final file
files.download("embedded_dataset.csv")