# -*- coding: utf-8 -*-
"""Notebook_3 GuardRail and LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZaEGWgAQ-WMl1LzMTBMowLBSM_93djYY
"""

# Installing dependencies
!pip install -q sentence-transformers faiss-cpu scikit-learn langchain langchain-huggingface huggingface_hub

import pandas as pd
import numpy as np
import faiss
import pickle
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from langchain_huggingface import HuggingFaceEndpoint
from langchain import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
import os

# Initializing conversation history
conversation_history = []

# Loading Dual Embeddings and FAISS Indices

# Load DataFrame
df = pd.read_pickle("dual_embeddings.pkl")

# Load FAISS Indices
index_minilm = faiss.read_index("faiss_minilm_cosine.index")
index_pubmed = faiss.read_index("faiss_pubmed_cosine.index")

print(f"Loaded dataset with shape: {df.shape}")
print(f"FAISS indexes loaded successfully.")

# Training Tiny Classifier for Category Prediction

# Extracting Questions and Categories
X = df['Question'].astype(str).fillna('')
y = df['Category']

# Converting Questions to TF-IDF Vectors
vectorizer = TfidfVectorizer(max_features=1000)
X_vect = vectorizer.fit_transform(X)

# Training Logistic Regression
classifier = LogisticRegression(max_iter=1000, class_weight="balanced")
classifier.fit(X_vect, y)

print("Tiny classifier trained for category prediction.")

# Saving the trained classifier and vectorizer
with open("tiny_classifier.pkl", "wb") as f:
    pickle.dump(classifier, f)

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("Saved tiny_classifier.pkl and vectorizer.pkl")

# Loading Embedding Models

# MiniLM embedding model
embed_model_minilm = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

# PubMedBERT embedding model
embed_model_pubmed = SentenceTransformer('neuml/pubmedbert-base-embeddings')

print("Embedding models loaded.")

# Predicting category from user query

def predict_category(query):
    vect = vectorizer.transform([query])
    return classifier.predict(vect)[0]

# FAISS Retrieval using PubMedBERT Index

def search_faiss_pubmed(user_query, top_k=50):
    user_vector = embed_model_pubmed.encode([user_query]).astype('float32')
    faiss.normalize_L2(user_vector)
    distances, indices = index_pubmed.search(user_vector, top_k)

    results = []
    for idx in indices[0]:
        row = df.iloc[idx]
        results.append({
            "question": row['Question'],
            "answer": row['Response'],
            "embedding_pubmed": row['embedding_pubmed'],
            "domain": row.get('Domain', "Unknown")
        })

    return results

# Re-ranking candidates using PubMedBERT

def rerank_with_pubmed(query, candidates, top_k=3):
    query_embed = embed_model_pubmed.encode([query]).astype('float32')

    similarities = []
    for candidate in candidates:
        candidate_embed = np.array(candidate['embedding_pubmed']).astype('float32')
        score = np.dot(query_embed, candidate_embed) / (np.linalg.norm(query_embed) * np.linalg.norm(candidate_embed))
        similarities.append(score)

    sorted_indices = np.argsort(similarities)[::-1]
    top_candidates = [candidates[int(i)] for i in sorted_indices[:top_k]]

    return top_candidates

# Building Structured Context for LLM

def build_context(candidates):
    context = ""
    for i, candidate in enumerate(candidates):
        context += f"- Q: {candidate['question']}\n  A: {candidate['answer']}\n"
    return context

!pip install openai
!pip install -q --upgrade langchain-openai

# Setting up LLM and Prompt Template

from langchain_openai import ChatOpenAI

# Setting OpenAI API key
os.environ["OPENAI_API_KEY"] = "YOUR_API_KEY" # Replace with an actual API key to load LLM

# OpenAI GPT-3.5 Turbo
llm = ChatOpenAI(
    model="gpt-3.5-turbo",
    temperature=0.01,
    max_tokens=500
)

# Prompt Template
prompt = PromptTemplate.from_template("""
You are a compassionate and supportive mental health therapist specializing in postpartum depression (PPD).

Your task is to provide warm, empathetic, and medically appropriate advice grounded in the counseling knowledge below.

- Keep your response brief (maximum 3-5 sentences).
- Be highly specific and actionable.
- Use a calming, non-judgmental, encouraging tone.
- Avoid generic platitudes. Tailor advice to the user's question.

{context}

User Question: {question}

Answer:
""")

# Defining Retrieval and Generation Pipeline

def retrieve_and_generate(user_query):
    global conversation_history

    # Retrieve candidates
    candidates = search_faiss_pubmed(user_query, top_k=50)

    # Remove duplicate questions
    seen_questions = set()
    unique_candidates = []
    for candidate in candidates:
        if candidate['question'] not in seen_questions:
            unique_candidates.append(candidate)
            seen_questions.add(candidate['question'])

    # Calculating semantic similarity
    user_embed = embed_model_minilm.encode([user_query]).astype('float32')
    similarities = []
    for candidate in unique_candidates:
        candidate_embed = embed_model_minilm.encode([candidate['question']]).astype('float32')
        score = np.dot(user_embed, candidate_embed.T) / (np.linalg.norm(user_embed) * np.linalg.norm(candidate_embed))
        similarities.append(score)

    max_similarity = float(max(similarities)) if similarities else 0.0
    print(f"Max similarity to retrieved docs: {max_similarity:.2f}")

    # Predicting category
    predicted_category = predict_category(user_query)
    print(f"Predicted Category: {predicted_category}")

    # Guardrail
    if predicted_category == "Uncategorized" and max_similarity < 0.50:
        return "I'm sorry, I specialize in postpartum depression support. Your question seems outside my area of expertise. Please consult a specialist."

    # Rerank with PubMedBERT
    top_candidates = rerank_with_pubmed(user_query, unique_candidates, top_k=3)

    # Build structured context
    structured_context = build_context(top_candidates)

    # Add conversation memory
    history_text = ""
    for turn in conversation_history:
        history_text += f"User: {turn['user']}\nBot: {turn['bot']}\n"

    # Full context for LLM
    full_context = history_text + "\nRelevant Counseling Knowledge:\n" + structured_context

    # Assembling final input for LLM
    chain = (
        {"context": lambda _: full_context, "question": RunnablePassthrough()}
        | prompt
        | llm
        | StrOutputParser()
    )

    # Generating response
    response = chain.invoke(user_query)

    # Saving conversation history
    conversation_history.append({"user": user_query, "bot": response})

    return response

# Defining Chatbot Loop

def chatbot_run():
    print("Welcome to MOMCare Postpartum Depression Support Chatbot!")
    print("Type 'stop' anytime to end the conversation.\n")

    while True:
        user_query = input("You: ")

        if user_query.strip().lower() in ['stop', 'exit', 'quit']:
            print("\nThank you for chatting with MOMCare. Take care!")
            break

        # Getting chatbot response
        bot_response = retrieve_and_generate(user_query)

        print(f"\nMOMCare Bot: {bot_response}\n")

# Running the Chatbot

chatbot_run()

import pandas as pd

def batch_generate_responses(input_excel_path, output_csv_path):
    # Load questions from Excel
    df_questions = pd.read_excel(input_excel_path)

    # Check if there is a column named 'Question'
    if 'Question' not in df_questions.columns:
        raise ValueError("The Excel file must have a 'Question' column.")

    # Create a list to hold results
    results = []

    print(f"Processing {len(df_questions)} questions...\n")

    for idx, row in df_questions.iterrows():
        user_question = row['Question']
        print(f"Processing Question {idx+1}: {user_question}")

        try:
            # Main generation call
            bot_response = retrieve_and_generate(user_question)
        except Exception as e:
            print(f"Error processing question {idx+1}: {e}")
            bot_response = "Error generating response."

        results.append({
            "Question": user_question,
            "Bot Response": bot_response
        })

    # Convert results to a DataFrame
    df_results = pd.DataFrame(results)

    # Save the results to CSV
    df_results.to_csv(output_csv_path, index=False)
    print(f"\nFinished! Responses saved to {output_csv_path}")

# Run the batch generation
batch_generate_responses("PPD_Questions.xlsx", "PPD_Generated_Responses.csv")

# Install Gradio if not already installed
!pip install gradio --quiet

import gradio as gr

# Make sure global variables are initialized BEFORE Gradio
conversation_history = []  # global conversation history

def gradio_chatbot(user_message, chat_history):
    global conversation_history

    if not user_message.strip():
        return "", chat_history

    try:
        bot_response = retrieve_and_generate(user_message)
    except Exception as e:
        print(f"Error inside chatbot: {e}")
        bot_response = "I'm sorry, I encountered an error. Please try again."

    conversation_history.append({"user": user_message, "bot": bot_response})

    chat_history.append(
        (f"🧑‍🍼 **You:** {user_message}", f"👩‍⚕️ **MOMCare:** {bot_response}")
    )

    return "", chat_history

def reset_conversation():
    global conversation_history
    conversation_history = []
    return []

with gr.Blocks() as demo:
    gr.Markdown("""
    # 👩‍⚕️ MOMCare: Postpartum Depression Support
    _Compassionate support for new mothers._ 🤱

    Feel free to share how you're feeling, or ask any questions. 💬
    """)

    chatbot = gr.Chatbot(
        label="MOMCare Support Chat",
        height=350,     # SMALLER window
        bubble_full_width=False
    )

    with gr.Row():
        with gr.Column(scale=8):
            user_input = gr.Textbox(
                placeholder="Type your message here...",
                show_label=False,
                lines=1,
                max_lines=3,
            )
        with gr.Column(scale=2):
            submit_btn = gr.Button("Send", variant="primary")
            clear_btn = gr.Button("Clear Chat", variant="secondary")

    submit_btn.click(gradio_chatbot, [user_input, chatbot], [user_input, chatbot])
    clear_btn.click(reset_conversation, outputs=[chatbot])

demo.launch(share=True)

from IPython.display import Javascript
Javascript('''
function ClickConnect(){
    console.log("Clicking");
    document.querySelector("colab-connect-button").click()
}
setInterval(ClickConnect, 60000)
''')

import time

while True:
    print("Running to keep the session alive...")
    time.sleep(60)  # Wait for 60 seconds